name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the build number
        id: build_number
        run: echo "::set-output name=build_number::${{ github.run_number }}"

      - name: Build Docker image for AMD64
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t wesaleldsokey/nodejs:${{ steps.build_number.outputs.build_number }}-amd64 \
            .
        shell: bash

      - name: Push Docker image for AMD64
        run: docker push wesaleldsokey/nodejs:${{ steps.build_number.outputs.build_number }}-amd64
